### PR TITLE
fix: vue error & SharedArrayBuffer is not defined

### PR DESCRIPTION
**Pull request by lecepin**
Fix the following issues #170 #111 #15 .

Please help with code review @vinayakkulkarni.

Xnip2022-03-19_20-08-41

image

### CODE REVIEW

**Comment by lecepin** [comment]
Hi @vinayakkulkarni ,If there is no problem with the code, can it be merged?

**Comment by vinayakkulkarni** [comment]
> Hi @vinayakkulkarni ,If there is no problem with the code, can it be merged?

I’ll take a look at the code & test it once tonight and revert

**Comment by douglas444** [comment]
> > Hi @vinayakkulkarni ,If there is no problem with the code, can it be merged?
> 
> I’ll take a look at the code & test it once tonight and revert

Any advance?

**Review by vinayakkulkarni — APPROVED** [review]
LGTM

**Pull request merged**
